# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppToYou' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppToYou
  pod 'CoreStore', '~> 8.0'
  pod 'R.swift'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Parchment', '~> 3.0'
  pod 'PopupDialog', '~> 1.1'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod 'XCoordinator', '~> 2.0'
  pod 'KeychainAccess'
  pod 'DropDown'
  pod 'FittedSheets'

end
